// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3hsvD2w-bdTbyvLa24l2KdNXSiMbOnPw',
    appId: '1:41727049586:web:89c42658e8a6eccb6567eb',
    messagingSenderId: '41727049586',
    projectId: 'sabir-darzi',
    authDomain: 'sabir-darzi.firebaseapp.com',
    storageBucket: 'sabir-darzi.firebasestorage.app',
    measurementId: 'G-009PBJ9KSN',
    databaseURL: 'https://sabir-darzi-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDroXjXR8U0dQOHh-qQBF58aiXGzooq3I8',
    appId: '1:41727049586:android:758ed87c2c4698bb6567eb',
    messagingSenderId: '41727049586',
    projectId: 'sabir-darzi',
    storageBucket: 'sabir-darzi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7QP3TzhXWGc6buOD4UOUtIdPLIbXoUBs',
    appId: '1:41727049586:ios:3ec2cbc2abc0bf5f6567eb',
    messagingSenderId: '41727049586',
    projectId: 'sabir-darzi',
    storageBucket: 'sabir-darzi.firebasestorage.app',
    iosBundleId: 'com.example.sabitTailor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7QP3TzhXWGc6buOD4UOUtIdPLIbXoUBs',
    appId: '1:41727049586:ios:3ec2cbc2abc0bf5f6567eb',
    messagingSenderId: '41727049586',
    projectId: 'sabir-darzi',
    storageBucket: 'sabir-darzi.firebasestorage.app',
    iosBundleId: 'com.example.sabitTailor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3hsvD2w-bdTbyvLa24l2KdNXSiMbOnPw',
    appId: '1:41727049586:web:32d01d27c6c544a76567eb',
    messagingSenderId: '41727049586',
    projectId: 'sabir-darzi',
    authDomain: 'sabir-darzi.firebaseapp.com',
    storageBucket: 'sabir-darzi.firebasestorage.app',
    measurementId: 'G-T08M6QRTJN',
  );
}
